UNID: "HG008_Element_lnginsert"
REFIDS: ["GRCh37","GRCh38-GIABv3", "CHM13V2"]
REF:
  GRCh37: /scratch2/resources/hs37d5.fa.gz
  GRCh38-GIABv3: /scratch2/resources/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz
  CHM13V2: /scratch2/resources/chm13v2.0_maskedY_rCRS.fa.gz
SAMPLES:
  [
  "HG008-N-D_ND_Long",
  "HG008-N-P_NP_Long" 
  ]
THREADS:
  bwa: 7
  samstat : 4
READPAIRS:
  HG008-N-D_ND_Long:
    read_group:
      ID: "HG008-N-D_KOL-0807"
      CN: "Element"
      SM: "HG008-N-D"
      PL: "Aviti_UltraQ"
      DT: 2024     
    R1: /scratch2/Element_HG008_20240626/Element_lnginsert/HG008-N-D/ND_Long/ND_Long_R1.fastq.gz
    R2: /scratch2/Element_HG008_20240626/Element_lnginsert/HG008-N-D/ND_Long/ND_Long_R2.fastq.gz
  HG008-N-P_NP_Long:
    read_group:
      ID: "HG008-N-P_KOL-0808"
      CN: "Element"
      SM: "HG008-N-P"
      PL: "Aviti_UltraQ"
      DT: 2024     
    R1: /scratch2/Element_HG008_20240626/Element_lnginsert/HG008-N-P/NP_Long/NP_Long_R1.fastq.gz
    R2: /scratch2/Element_HG008_20240626/Element_lnginsert/HG008-N-P/NP_Long/NP_Long_R2.fastq.gz
